[package]
name = "sha2-const"
version = "0.1.0"
authors = ["Saleem Rashid <dev@saleemrashid.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
hex = "0.4.2"
proptest = "0.9.6"
sha2 = "0.8.1"
